In [7]:
import numpy as np
np.random.seed(1)
np.random.random()


0.417022004702574

In [11]:
np.random.uniform(1,2)

1.1467558908171132

In [12]:
np.random.uniform(1,100,10)

array([10.14152088, 19.43976093, 35.21051198, 40.27997995, 54.34285667,
       42.50025693, 68.83673054, 21.24077272, 87.9336262 ,  3.71137173])

In [13]:
np.random.uniform(1,100,10).reshape(2,5)

array([[67.37628351, 42.31317543, 56.31029302, 14.89830692, 20.61204742],
       [80.2737123 , 96.857896  , 32.02899364, 69.53993895, 87.76252608]])

In [14]:
np.random.randint(1,10,15).reshape(3,5)

array([[2, 9, 9, 4, 9],
       [8, 4, 7, 6, 2],
       [4, 5, 9, 2, 5]])

In [18]:
a=np.random.randint(1,10,6)
a

array([8, 5, 6, 4, 7, 9])

In [19]:
np.max(a)

9